SELECT CONCAT(Name, '(' , LEFT(OCCUPATION,1) ,')') as N from occupations order by n;

SELECT CONCAT('There are a total of ',COUNT(OCCUPATION),' ',LOWER(OCCUPATION),'s.')
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION), OCCUPATION;